CREATE TABLE Usuarios (
	id SERIAL PRIMARY KEY, 
	nombre VARCHAR(30) NOT NULL,
	apellido VARCHAR(30) NOT NULL,
	email VARCHAR(30) UNIQUE NOT NULL,
	rut VARCHAR(20) UNIQUE NOT NULL,
	password VARCHAR(255) NOT NULL,
	region VARCHAR(100) NOT NULL,
	comuna VARCHAR(100) NOT NULL
)